---
engines:
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
exclude_paths:
- config/
- db/
- spec/
- test/
- vendor/
- public/
