language: ruby
rvm:
  - 2.3.1
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  - bundle exec rspec spec/
addons:
  code_climate:
    repo_token: e9480d812300ee7bc488f0f19335839d32ac9c47aad69b7ad05f78468968aec9
